nosana:
  description: Solana hello world program

global:
  image: nosana/solana:v1.0.3

  trigger:
    branch:
      - master

jobs:
  - name: build program
    commands:
      - npm run build:program-rust
    artifacts:
      - name: program
        path: dist/program/helloworld.so

  - name: write buffer
    environment:
      SOLANA_WALLET:
        type: nosana/secret
        endpoint: https://secrets.k8s.dev.nos.ci/
        value: SOLANA_WALLET
    commands:
      - mkdir solana
      - echo $SOLANA_WALLET > solana/private-key.json
      - solana config set --url devnet --keypair solana/private-key.json
      - solana address > solana/spill.txt
      - solana program write-buffer /dist/helloworld.so | tee solana/buffer.txt
    resources:
      - name: program
        path: /dist
    artifacts:
      - name: solana
        path: solana

  - name: squads deploy
    image: node:16
    commands:
      - echo $(< solana/buffer.txt)
      - echo $(< solana/spill.txt)
      - |
        node scripts/createProgramUpdate.js  \
          --name upgradeTest \
          --private-key solana/private-key.json \
          --buffer $(< solana/buffer.txt) \
          --spill $(< solana/spill.txt) \
          --multisig 3TsTokHbDvRqsymuC5LZrK2NkUQG2LHxAShydPY2A1Cj \
          --program GmpDbY3M5KXM9TPooZziM7SC5rT9YZZ1sf3AfTcyZwAs \
          --authority 9HgALjiPNoh7TbCP7h5FRUFggD1q3UjLfiU9AbTGmSGc
    resources:
      - name: solana
        path: /solana
