nosana:
  description: Solana hello world

global:
  image: nosana/solana:v1.0.3

  trigger:
    branch:
      - master

jobs:
  - name: build
    commands:
      - npm run build:program-rust
      - ls -lah
    artifacts:
      - name: dist
        path: ./dist/

  - name: deliver
    commands:
      - ls -lah /
      - ls -lah
      - ls program**
    resources:
      - name: dist
        path: ./dist/
