nosana:
  description: Solana hello world

global:
  image: nosana/solana:v1.0.2

  trigger:
    branch:
      - master

jobs:
  - name: build
    commands:
      - npm run build:program-rust
    artifacts:
      - name: program
        path: dist/program
