nosana:
  description: Solana Build Template

global:
  image: nosana/solana:v1.0.6

  trigger:
    branch:
      - master

jobs:
  - name: build program
    commands:
      - ls 
      - lah
      - npm ci
      - npm run build:program-rust
      - ls -lah
      - npm run test:program-test
      - Echo Done