nosana:
  description: Solana hello world

global:
  image: nosana/solana:v1.0.3

  trigger:
    branch:
      - master

jobs:
  - name: build
    commands:
      - npm run build:program-rust
    artifacts:
      - name: program
        path: dist/program

  - name: deliver
    environment:
      SOLANA_WALLET:
        type: nosana/secret
        endpoint: https://secrets.k8s.dev.nos.ci/
        value: SOLANA_WALLET
    commands:
      - echo $SOLANA_WALLET > key.json
      - solana config set -u d
      - solana config set -k $(pwd)/key.json
      - solana config get
      - solana program write-buffer -k key.json -u d dist/program/helloworld.so
    resources:
      - name: program
        path: ./
