nosana:
  description: Nosana Blank Template

global:
  image: alpine:latest

  trigger:
    branch:
      - master

jobs:
  - name: Create README
    commands:
    - echo "Hello Build Station"
    - pwd
    - ls
    - env