
nosana:
  description: Solana hello world

global:
  image: nosana/solana:v1.0.3

  trigger:
    branch:
      - master

jobs:
  - name: build
    commands:
      - npm run build:program-rust
    artifacts:
      - name: program
        path: dist/program/helloworld.so

  - name: deliver
    commands:
      - ls -lah
      - ls /
    resources:
      - name: program
        path: dist