nosana:
  description: Solana Build Template

global:
  image: nosana/solana

  trigger:
    branch:
      - master

jobs:
  - name: build program
    commands:
      - ls -lah
      - npm ci
      - npm run build:program-rust
      - ls -lah
#       - npm run test:program-rust
      - echo Done
