nosana:
  description: Nosana-Node Pipeline

global:
 # projectserum/build:v0.26.0
  image: registry.hub.docker.com/projectserum/build:v0.26.0

  trigger:
    branch:
      - master

jobs:
  - name: Hello World Solana
    commands:
      - ls
      - npm install
    artifacts:
      - name: program
        path: dist/
      - name: npm
        path: node_modules
        
  - name: Lint
    commands:
      - npm run lint
    resources:
      - name: program
        path: ./
      - name: npm
        path: ./
    
  - name: Test Solana
    commands:
      - ls
      - npm run test:program-rust
    resources:
      - name: program
        path: ./
      - name: npm
        path: ./
        
#  - name: Deploy to Solana Devnet
#    commands:
#      - sudo solana-keygen new -o /root/.config/solana/id.json
#      - solana airdrop 1 --url devnet
#      - solana program write-buffer ./dist/program/helloworld.so  --url devnet
    
    
      