nosana:
  description: Nosana-Node Pipeline

global:
 # projectserum/build:v0.26.0
  image: registry.hub.docker.com/projectserum/build:v0.26.0

  trigger:
    branch:
      - master

jobs:
  - name: Hello World Solana
    commands:
      - ls
      - npm install
    artifacts:
      - name: npm
        path: ./node_modules
        
  - name: Lint
    commands:
      - npm run lint
    resources:
      - name: npm
        path: ./
    
  - name: Test Solana
    commands:
      - ls
      - npm run test:program-rust
    resources:
      - name: npm
        path: ./
      