nosana:
  description: Nosana-Node Pipeline

global:
 # projectserum/build:v0.26.0
  image: registry.hub.docker.com/projectserum/build:v0.26.0

  trigger:
    branch:
      - master

jobs:
  - name: Hello World Solana
    commands:
      - ls
      - npm install
      - npm run build:program-rust
      - solana-keygen new -o /root/.config/solana/id.json
      - solana airdrop 1 --url devnet
      - solana program write-buffer ./dist/program/helloworld.so  --url devnet

      