# .nosana-ci.yml
nosana:
  description: Solana hello world

global:
  image: solanalabs/rust

  trigger:
    branch:
      - master

jobs:
  - name: build
    commands:
      - sh -c "$(curl -sSfL https://release.solana.com/v1.15.2/install)"
      - npm run build:program-rust
    artifacts:
      - name: program
        path: dist/program
